version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --expect-workers 2

  worker1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  worker2:
    image: locustio/locust
    volumes:
     - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

# Command :
  #docker version
  #docker ps
  #docker run -p 8089:8089 -v $PWD:/mnt/locust -d locustio/locust -f /mnt/locust/locustfile.py
  #docker ps
  #docker compose up
